#!/bin/bash
set -e

ShowUsage() {
    echo "Usage: $0 [VM name OR -list]"
    echo
    echo "Use -list to list VMs available"
}

ListVMs() {
    ls /home/$(whoami)/vcpu | grep .vcpu
}

sudo echo "vcpu v1.0.4"

if [ -z "$1" ] && [ "$1" != "-list" ]; then
    ShowUsage
    exit 0
fi

if [[ "$1" == "-list" ]]; then
    ListVMs
    exit 0
fi


VMsettings="$(cat /home/$(whoami)/vcpu/$1.vcpu)"
MemSize=$(echo $VMsettings | cut -d '|' -f 1)
CDfile=$(echo $VMsettings | cut -d '|' -f 2)
BootFrom=$(echo $VMsettings | cut -d '|' -f 3)

qemu-system-x86_64 -cpu qemu64 -m $MemSize -cdrom $CDfile -boot $BootFrom -drive file=/home/$(whoami)/vcpu/$1.vhd,format=raw -smp 2 -vga vmware

if [[ "$BootFrom" != "c" ]]; then
    echo "Did you finish installing the OS? (y/n)"
    read answer
    if [[ "$answer" == "y" || "$answer" == "Y" ]]; then
        echo "$MemSize|$CDfile|c" > "/home/$(whoami)/vcpu/$1.vcpu"
    elif [[ "$answer" == "n" || "$answer" == "N" ]]; then
        echo "Okay."
        exit 0
    else
        echo "Invalid input. Please enter 'y' or 'n'."
        exit 1
    fi
fi